using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Magic_Shop
{
	public class Names
	{
		Random random = new Random();
		public List<string> storeNamesFunny = new List<string>
		{
			"General Goode's General Goods",
			"The Broken Drum",
			"The Philosopher's Scone",
			"The Halberdashery",
			"Dewey, Cheetham & Howe",
			"Al Ligori's Bookshop",
			"Gnome Depot",
			"Shell of a Man",
			"Going Ballistic",
			"Scroll Up",
			"Nick's Nacks",
			"Breaking Point",
			"Takes Guts",
			"Knife in the Road",
			"Barnes the Noble",
			"Loot Locker",
			"Mace's",
			"Quest Buy",
			"Crazy Hassan's Used Camels",
			"Honest Ali's Used Saurus Lot",
			"Guitar Centaur",
			"The Sharper Mirror Image",
			"The Sharper Mage",
			"Peter Piper's Potent Potables",
			"Abercrombie and Witch",
			"Murders and Acquisitions",
			"The Superb Owl",
			"Smithy Wesson",
			"War Mart",
			"The Cheesecake Phylactory",
			"Cone of Cold Creamery",
			"Hogg and Dawes",
			"Wesson's Smithy",
			"Orbs! Orbs! Orbs!",
			"Crate and Barrel",
			"Helmut's Helmets",
			"Tier 1 Imports",
			"Bloomin' Dales",
			"Urbane Outfitters",
			"Estee's Larder",
			"Louie's Batons",
			"Pack's 5th Avenue",
			"Tombs To Go",
			"Divine Consign",
			"Chaotic Frugal",
			"Lighter Fighter",
			"Kobold or Go Home!",
			"He Whom Smelt It",
			"Arm and Hammer",
			"Levi and Strauss",
			"Black and Decker",
			"Baldur's Mouth",
			"The Calim Jewel Emporium",
			"Candlekeep Chandlery",
			"The Counting House",
			"Danthelon's Dancing Axe",
			"Felogyr's Fireworks",
			"Garmults's House of Mastery",
			"Hamhock's Slaughterhouse",
			"Harbreeze Bakery",
			"The Hissing Stones",
			"Sorcerous Sundries",
			"Illgott and Gaines"
		};
		public List<string> storeNameAdjectives = new List<string>
		{
			"Adjective",
			"Fat",
			"Bent",
			"Green",
			"Silver",
			"Homely",
			"Fabulous",
			"Cormyrean",
			"Dandy",
			"Hungry",
			"Blasted",
			"Vermillion",
			"Wide",
			"White",
			"Black",
			"Splendid",
			"Silky",
			"Proud",
			"Vicious",
			"Screeching",
			"Smiling",
			"Dying",
			"Killing",
			"Wandering",
			"Hanged",
			"Dozing",
			"Fighting",
			"Dancing",
			"Pilfering",
			"Marauding",
			"Bantering",
			"Eating",
			"Salty",
			"Smoking",
			"Heavy",
			"Icy",
			"Striped",
			"Sleepy",
			"Hissing",
			"Defiant",
			"Ugly",
			"Lucky",
			"Grumpy",
			"Old",
			"Stout",
			"Crafty",
			"Bold",
			"Drunken",
			"Sleeping",
			"Hearty",
			"Buxom",
			"Blind",
			"Crazy",
			"Honest",
			"Frowning",
			"Blinking",
			"Wandering",
			"Welcoming",
			"Merry",
			"Good",
			"Lucky",
			"Laughing",
			"Beautiful",
			"Blue-eyed",
			"Flying",
			"Gallant",
			"Fair",
			"Dancing",
			"Prancing",
			"Happy",
			"Wet",
			"Half",
			"Red",
			"Secret",
			"Black",
			"Short",
			"Buried",
			"Gray",
			"Crossed",
			"Honored",
			"Broken",
			"Fireside",
			"Yellow",
			"Two",
			"Three",
			"Four",
			"Five",
			"Burning",
			"Six",
			"Seven",
			"Frozen",
			"Ashen",
			"Sweet",
			"Hidden",
			"Shining",
			"White",
			"Royal",
			"Rusty",
			"Green",
			"Wooden",
			"Blue",
			"Ancient",
			"Mystic",
			"Runic",
			"Cryptic",
			"Magical",
			"Divine",
			"Arcane",
			"Mystic",
			"Secret",
			"Sorcerous",
			"Iron",
			"Steel",
			"Mithril",
			"Brass",
			"Copper",
			"Bronze",
			"Silver",
			"Gold",
			"Platinum",
			"Adamantine",
			"Electrum"
		};
		public List<string> storeNameNouns = new List<string>
		{
			"Noun",
			"Goblin",
			"Lady",
			"Mule",
			"Boy",
			"Dwarf",
			"Elf",
			"Lord",
			"Wizard",
			"Dragon",
			"Ogre",
			"Giant",
			"Manticore",
			"Drake",
			"Porcupine",
			"Knight",
			"Minotaur",
			"Halfling",
			"Devil",
			"Girl",
			"Treant",
			"Rod",
			"Sword",
			"Noose",
			"Wagon",
			"Mug",
			"Pie",
			"Table",
			"Throne",
			"Boot",
			"Pot",
			"Banner",
			"Cart",
			"Barrel",
			"Moon",
			"Brazier",
			"Dagger",
			"Axe",
			"Lance",
			"Crown",
			"Star",
			"Serpent",
			"Badger",
			"Frog",
			"Dragon",
			"Rat",
			"Boar",
			"Mole",
			"Vole",
			"Bat",
			"Hound",
			"Ram",
			"Hog",
			"Pig",
			"Bear",
			"Monster",
			"Eel",
			"Beholder",
			"Goat",
			"Bull",
			"Lion",
			"Spider",
			"Cock",
			"Tiger",
			"Hare",
			"Wolf",
			"Horse",
			"Bee",
			"Raven",
			"Eagle",
			"Cat",
			"Phoenix",
			"Owl",
			"Fox",
			"Hawk",
			"Pegasus",
			"Drake",
			"Swan",
			"Stag",
			"Harpy",
			"Falcon",
			"Unicorn",
			"Gryphon",
			"Den",
			"Burrow",
			"Lair",
			"Hole",
			"Patch",
			"Web",
			"Lodge",
			"Briar",
			"Nest",
			"Eyrie",
			"Clan",
			"Guild",
			"Keep",
			"Camp",
			"Bailey",
			"Bridge",
			"Gate",
			"Castle",
			"Donjon",
			"Ford",
			"Balcony",
			"Abby",
			"Home",
			"Room",
			"Dale",
			"Barn",
			"Galley",
			"Moor",
			"Grove",
			"Court",
			"Palace",
			"Garden",
			"Forest",
			"House",
			"Lodge",
			"Manor",
			"Vale",
			"Meadow",
			"Coliseum",
			"Lamp",
			"Barrel",
			"Ale",
			"Horn",
			"Earth",
			"Nail",
			"Arms",
			"Cleaver",
			"Anvil",
			"Mug",
			"Rock",
			"Boot",
			"Stone",
			"Cork",
			"Anchor",
			"Fire",
			"Basket",
			"Book",
			"Coal",
			"Bell",
			"Bottle",
			"Candle",
			"Ash",
			"Cup",
			"Water",
			"Hammock",
			"Tun",
			"Cobblestone",
			"Broom",
			"Cart",
			"Board",
			"Skull",
			"Crown",
			"Lily",
			"Star",
			"Lotus",
			"Rod",
			"Crystal",
			"Sun",
			"Oak",
			"Flute",
			"Acorn",
			"Air",
			"Staff",
			"Harp",
			"Rose",
			"Ring",
			"Wand",
			"Moon",
			"Elm",
			"Warrior",
			"Brewer",
			"Baker",
			"Priest",
			"Merchant",
			"Lad",
			"Lass",
			"Smith",
			"Hero",
			"Witch",
			"Corsair",
			"Paladin",
			"Beggar",
			"Hag",
			"Brigand",
			"Sister",
			"Father",
			"Mother",
			"Jester",
			"Elf",
			"Halfling",
			"Dwarf",
			"Gnome",
			"Angel",
			"Mariner",
			"Druid",
			"Lady",
			"Lord",
			"Scholar",
			"Wizard",
			"Knight",
			"Archer",
			"Dancer",
			"Woodsman",
			"Harper",
			"Bard",
			"Runestone",
			"Book",
			"Tome",
			"Manual",
			"Text",
			"Parchment",
			"Scroll",
			"Folio",
			"Script",
			"Page",
			"Gauntlet",
			"Axe",
			"Pick",
			"Helm",
			"Hammer",
			"Pike",
			"Mace",
			"Flail",
			"Bolt",
			"Hatchet",
			"Blade",
			"Spur",
			"Mail",
			"Jerkin",
			"Spear",
			"Dagger",
			"Arrow",
			"Shield",
			"Lance",
			"Sword",
			"Buckler",
			"Sausage",
			"Ale",
			"Roast",
			"Mead",
			"Cabbage",
			"Mushroom",
			"Soup",
			"Pepper",
			"Cheese",
			"Bread",
			"Rye",
			"Barley",
			"Fowl",
			"Cream",
			"Pastry",
			"Berry",
			"Apple",
			"Wine",
			"Milk",
			"Cake"
		};

		public string generateRandomStoreName()
		{
			string randomNameAdj = storeNameAdjectives[random.Next(0, storeNameAdjectives.Count())];
			string randomNameNoun = storeNameNouns[random.Next(0, storeNameNouns.Count())];
			return "The " + randomNameAdj + " " + randomNameNoun;
		}

		public string generateFunnyStoreName()
		{
			return storeNamesFunny[random.Next(0, storeNamesFunny.Count())];
		}

	}
}
